services:

  currency-naming-server:
    image: sid21/currency-naming-server:latest
    mem_limit: 700m
    ports:
      - "5000:5000"
    networks:
      - currency-network
    
  currency-config-server:
    image: sid21/currency-config-server:latest
    mem_limit: 700m
    ports:
      - "8888:8888"
    networks:
      - currency-network
    depends_on:
      - currency-naming-server
    environment:
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://currency-naming-server:5000/eureka
      - SPRING.CLOUD.CONFIG.SERVER.GIT.URI=file:///git-config
    volumes:
      - type: bind
        source: C:\\Users\\sid0x\\Documents\\spring_microservices_workspace\\git_local_config_repository
        target: /git-config

  currency-api-gateway:
    image: sid21/currency-api-gateway:latest
    mem_limit: 700m
    ports:
      - "80:80"
    networks:
      - currency-network
    depends_on:
      - currency-naming-server
    environment:
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://currency-naming-server:5000/eureka

  currency-exchange-service:
    image: sid21/currency-exchange-service:latest
    mem_limit: 700m
    ports:
      - "8110:8110"
    networks:
      - currency-network
    depends_on:
      - currency-naming-server
    environment:
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://currency-naming-server:5000/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/converterDB
      - SPRING.CONFIG.IMPORT=optional:configserver:http://currency-config-server:8888    
    
  currency-conversion-service:
    image: sid21/currency-conversion-service:latest
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - currency-naming-server
    environment:
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://currency-naming-server:5000/eureka
      - SPRING.CONFIG.IMPORT=optional:configserver:http://currency-config-server:8888

networks:
  currency-network: