version: '3.7'

services:

  currency-naming-service:
    image: sid21/currency-naming-server:latest
    mem_limit: 500m
    ports:
      -"5000:5000"
    networks:
      - currency-network
    
  currency-config-service:
    image: sid21/currency-config-server:latest
    mem_limit: 500m
    ports:
      -"8888:8888"
    networks:
      - currency-network
    depends_on:
    - currency-naming-server
    environment:
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://currency-naming-server:5000/eureka

  currency-api-gateway:
    image: sid21/currency-api-gateway:latest
    mem_limit: 500m
    ports:
      -"80:80"
    networks:
      - currency-network
    depends_on:
    - currency-naming-server
    environment:
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://currency-naming-server:5000/eureka

  currency-exchange-service:
    image: sid21/currency-exchange-service:latest
    mem_limit: 500m
    ports:
      -"8110:8110"
    networks:
      - currency-network
    depends_on:
    - currency-naming-server
    environment:
    - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://currency-naming-server:5000/eureka

  currency-conversion-service:
    image: sid21/currency-conversion-service:latest
    mem_limit: 500m
    ports:
      -"8100:8100"
    networks:
      - currency-network
    depends_on:
      - currency-naming-server
    environment:
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://currency-naming-server:5000/eureka

networks:
  currency-network: